# -*- mode: python ; coding: utf-8 -*-

from pathlib import Path


project_root = Path.cwd()

a = Analysis(
    ["main.py"],
    pathex=[str(project_root)],
    binaries=[],
    datas=[
        (str(project_root / "configs" / "llm_api"), "configs/llm_api"),
        (str(project_root / "assets"), "assets"),
    ],
    hiddenimports=[
        "av",
        "ctranslate2",
        "f5_tts",
        "f5_tts.api",
        "f5_tts.model",
        "f5_tts.model.cfm",
        "f5_tts.model.dataset",
        "f5_tts.model.modules",
        "f5_tts.model.trainer",
        "f5_tts.model.utils",
        "f5_tts.socket_client",
        "f5_tts.socket_server",
        "faster_whisper",
        "chatterbox",
        "chatterbox.tts",
        "chatterbox.mtl_tts",
        "huggingface_hub",
        "neucodec",
        "torchao",
        "piper",
        "perth",
        "pyttsx3",
        "sea_g2p",
        "sherpa_onnx",
        "sounddevice",
        "torch",
        "transformers",
        "vieneu",
        "vieneu.base",
        "vieneu.factory",
        "vieneu.standard",
        "vieneu_utils",
        "vieneu_utils.core_utils",
        "vieneu_utils.phonemize_text",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="learning-agent",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
